Implemented tests for `PhpAmqpLibAmqpDriver` via proper matrix testing.
This allows running tests for all possible combinations of brokers vs
result backends - and both for running tests locally and for running
tests in Github Actions.

- Fixed a bug in `PhpAmqpLibAmqpDriver` discovered by these new tests
  where a pidbox exchange was being declared as `durable`, which is not
  how Celery declares it and that was causing this kind of error:

  ```
  AMQPProtocolChannelException: PRECONDITION_FAILED - inequivalent arg
  'durable' for exchange 'celery.pidbox' in vhost '/': received 'true'
  but current is 'false'
  ```